// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// app/layout.js
// app/layout.js
// import { AuthProvider } from './components/AuthContext'; // Adjust the path if needed
// import { Inter } from 'next/font/google'; // Optional: Use Google Fonts if needed
// import './globals.css'; // Import global styles if you have any

// // Optional: Google font setup
// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Your App Title',
//   description: 'Your app description',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <AuthProvider>
//           <main>{children}</main>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
import { Analytics } from "@vercel/analytics/react"
import { AuthProvider } from './components/AuthContext'; // Ensure this path is correct

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
           </AuthProvider>
        <Analytics />
      </body>
    </html>
  );
}
